name: 'Notify Slack of Build Status'
description: 'Send notifications to Slack of the current build status'
inputs:
  job-status:
    description: 'Current job status of the build'
  slack-bot-token:
    description: 'Bot token used to send messages'
  slack-channel:
    description: 'Destination channel to send messages'
runs:
  using: 'node20'
  main: 'index.js'
