on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-success:
    runs-on: ${{ fromJSON(vars.SWI_GLORG_PROD_UBUNTU_2204) }}
    name: Test the action on success
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Success
        run: exit 0

      - name: Action
        uses: ./
        if: always()
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}

  test-failure:
    runs-on: ${{ fromJSON(vars.SWI_GLORG_PROD_UBUNTU_2204) }}
    name: Test the action on failure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Failure
        run: exit 1

      - name: Action
        uses: ./
        if: always()
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
